version:  '2.3'

services:
    smartping:
      build: .
      extends:
          file: common.yml
          service: template
      volumes:
          - "./conf:/go/src/app/conf"
          - "./db:/go/src/app/db"
      ports:
          - "8899:8899"
